# This file has been generated by node2nix 1.8.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "formcore-js-0.1.39" = {
      name = "formcore-js";
      packageName = "formcore-js";
      version = "0.1.39";
      src = fetchurl {
        url = "https://registry.npmjs.org/formcore-js/-/formcore-js-0.1.39.tgz";
        sha512 = "Tk/KytCHmKRfyDNrjGCxcgIM7zBd9I04BAWV8Hck3dEAoStbM2IvJPvzJLo0LaxSdkgxO/fk0ESsGes1poPcWQ==";
      };
    };
  };
  args = {
    name = "formality-js";
    packageName = "formality-js";
    version = "0.2.64";
    src = ../bin/js;
    dependencies = [
      sources."formcore-js-0.1.39"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Formality Language in JavaScript";
      homepage = "https://github.com/moonad/formality#readme";
      license = "MIT";
    };
    production = false;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}